<?php

namespace ContainerUcGepDm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Y6liuS6Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.y6liuS6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.y6liuS6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Controller\\AllStatController::index' => ['privates', '.service_locator.2QlhDyF.App\\Controller\\AllStatController::index()', 'getAllStatControllerindexService', true],
            'App\\Controller\\DeveloperController::index' => ['privates', '.service_locator.Qqlvzhg.App\\Controller\\DeveloperController::index()', 'getDeveloperControllerindexService', true],
            'App\\Controller\\DeveloperController::new' => ['privates', '.service_locator.P.blNFL.App\\Controller\\DeveloperController::new()', 'getDeveloperControllernewService', true],
            'App\\Controller\\DeveloperController::edit' => ['privates', '.service_locator.WPvjtlV.App\\Controller\\DeveloperController::edit()', 'getDeveloperControllereditService', true],
            'App\\Controller\\DeveloperController::delete' => ['privates', '.service_locator.WPvjtlV.App\\Controller\\DeveloperController::delete()', 'getDeveloperControllerdeleteService', true],
            'App\\Controller\\ProjectController::index' => ['privates', '.service_locator.v7.tT8T.App\\Controller\\ProjectController::index()', 'getProjectControllerindexService', true],
            'App\\Controller\\ProjectController::new' => ['privates', '.service_locator.P.blNFL.App\\Controller\\ProjectController::new()', 'getProjectControllernewService', true],
            'App\\Controller\\ProjectController::show' => ['privates', '.service_locator.mlTFQ4a.App\\Controller\\ProjectController::show()', 'getProjectControllershowService', true],
            'App\\Controller\\ProjectController::edit' => ['privates', '.service_locator.F1tB7lc.App\\Controller\\ProjectController::edit()', 'getProjectControllereditService', true],
            'App\\Controller\\ProjectController::delete' => ['privates', '.service_locator.F1tB7lc.App\\Controller\\ProjectController::delete()', 'getProjectControllerdeleteService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Controller\\AllStatController:index' => ['privates', '.service_locator.2QlhDyF.App\\Controller\\AllStatController::index()', 'getAllStatControllerindexService', true],
            'App\\Controller\\DeveloperController:index' => ['privates', '.service_locator.Qqlvzhg.App\\Controller\\DeveloperController::index()', 'getDeveloperControllerindexService', true],
            'App\\Controller\\DeveloperController:new' => ['privates', '.service_locator.P.blNFL.App\\Controller\\DeveloperController::new()', 'getDeveloperControllernewService', true],
            'App\\Controller\\DeveloperController:edit' => ['privates', '.service_locator.WPvjtlV.App\\Controller\\DeveloperController::edit()', 'getDeveloperControllereditService', true],
            'App\\Controller\\DeveloperController:delete' => ['privates', '.service_locator.WPvjtlV.App\\Controller\\DeveloperController::delete()', 'getDeveloperControllerdeleteService', true],
            'App\\Controller\\ProjectController:index' => ['privates', '.service_locator.v7.tT8T.App\\Controller\\ProjectController::index()', 'getProjectControllerindexService', true],
            'App\\Controller\\ProjectController:new' => ['privates', '.service_locator.P.blNFL.App\\Controller\\ProjectController::new()', 'getProjectControllernewService', true],
            'App\\Controller\\ProjectController:show' => ['privates', '.service_locator.mlTFQ4a.App\\Controller\\ProjectController::show()', 'getProjectControllershowService', true],
            'App\\Controller\\ProjectController:edit' => ['privates', '.service_locator.F1tB7lc.App\\Controller\\ProjectController::edit()', 'getProjectControllereditService', true],
            'App\\Controller\\ProjectController:delete' => ['privates', '.service_locator.F1tB7lc.App\\Controller\\ProjectController::delete()', 'getProjectControllerdeleteService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\AllStatController::index' => '?',
            'App\\Controller\\DeveloperController::index' => '?',
            'App\\Controller\\DeveloperController::new' => '?',
            'App\\Controller\\DeveloperController::edit' => '?',
            'App\\Controller\\DeveloperController::delete' => '?',
            'App\\Controller\\ProjectController::index' => '?',
            'App\\Controller\\ProjectController::new' => '?',
            'App\\Controller\\ProjectController::show' => '?',
            'App\\Controller\\ProjectController::edit' => '?',
            'App\\Controller\\ProjectController::delete' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\AllStatController:index' => '?',
            'App\\Controller\\DeveloperController:index' => '?',
            'App\\Controller\\DeveloperController:new' => '?',
            'App\\Controller\\DeveloperController:edit' => '?',
            'App\\Controller\\DeveloperController:delete' => '?',
            'App\\Controller\\ProjectController:index' => '?',
            'App\\Controller\\ProjectController:new' => '?',
            'App\\Controller\\ProjectController:show' => '?',
            'App\\Controller\\ProjectController:edit' => '?',
            'App\\Controller\\ProjectController:delete' => '?',
        ]);
    }
}
