<?php

namespace ContainerUcGepDm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAllStatControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2QlhDyF.App\Controller\AllStatController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2QlhDyF.App\\Controller\\AllStatController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'projectRepository' => ['privates', 'App\\Repository\\ProjectRepository', 'getProjectRepositoryService', true],
            'developerRepository' => ['privates', 'App\\Repository\\DeveloperRepository', 'getDeveloperRepositoryService', true],
        ], [
            'projectRepository' => 'App\\Repository\\ProjectRepository',
            'developerRepository' => 'App\\Repository\\DeveloperRepository',
        ]))->withContext('App\\Controller\\AllStatController::index()', $container);
    }
}
