<?php

namespace ContainerUcGepDm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDeveloperControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Qqlvzhg.App\Controller\DeveloperController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Qqlvzhg.App\\Controller\\DeveloperController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'developerRepository' => ['privates', 'App\\Repository\\DeveloperRepository', 'getDeveloperRepositoryService', true],
        ], [
            'developerRepository' => 'App\\Repository\\DeveloperRepository',
        ]))->withContext('App\\Controller\\DeveloperController::index()', $container);
    }
}
